server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: order
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ceypetco
      auto-offset-reset: earliest